/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedServicesRouteImport } from './routes/embed/services'
import { Route as EmbedPriestsRouteImport } from './routes/embed/priests'
import { Route as EmbedCalendarRouteImport } from './routes/embed/calendar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedServicesRoute = EmbedServicesRouteImport.update({
  id: '/embed/services',
  path: '/embed/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedPriestsRoute = EmbedPriestsRouteImport.update({
  id: '/embed/priests',
  path: '/embed/priests',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedCalendarRoute = EmbedCalendarRouteImport.update({
  id: '/embed/calendar',
  path: '/embed/calendar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed/calendar': typeof EmbedCalendarRoute
  '/embed/priests': typeof EmbedPriestsRoute
  '/embed/services': typeof EmbedServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed/calendar': typeof EmbedCalendarRoute
  '/embed/priests': typeof EmbedPriestsRoute
  '/embed/services': typeof EmbedServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embed/calendar': typeof EmbedCalendarRoute
  '/embed/priests': typeof EmbedPriestsRoute
  '/embed/services': typeof EmbedServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/embed/calendar' | '/embed/priests' | '/embed/services'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/embed/calendar' | '/embed/priests' | '/embed/services'
  id:
    | '__root__'
    | '/'
    | '/embed/calendar'
    | '/embed/priests'
    | '/embed/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedCalendarRoute: typeof EmbedCalendarRoute
  EmbedPriestsRoute: typeof EmbedPriestsRoute
  EmbedServicesRoute: typeof EmbedServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/services': {
      id: '/embed/services'
      path: '/embed/services'
      fullPath: '/embed/services'
      preLoaderRoute: typeof EmbedServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/priests': {
      id: '/embed/priests'
      path: '/embed/priests'
      fullPath: '/embed/priests'
      preLoaderRoute: typeof EmbedPriestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/calendar': {
      id: '/embed/calendar'
      path: '/embed/calendar'
      fullPath: '/embed/calendar'
      preLoaderRoute: typeof EmbedCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedCalendarRoute: EmbedCalendarRoute,
  EmbedPriestsRoute: EmbedPriestsRoute,
  EmbedServicesRoute: EmbedServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
