/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedSpotlightRouteImport } from './routes/embed/spotlight'
import { Route as EmbedServicesRouteImport } from './routes/embed/services'
import { Route as EmbedPriestsRouteImport } from './routes/embed/priests'
import { Route as EmbedCalendarRouteImport } from './routes/embed/calendar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedSpotlightRoute = EmbedSpotlightRouteImport.update({
  id: '/embed/spotlight',
  path: '/embed/spotlight',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedServicesRoute = EmbedServicesRouteImport.update({
  id: '/embed/services',
  path: '/embed/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedPriestsRoute = EmbedPriestsRouteImport.update({
  id: '/embed/priests',
  path: '/embed/priests',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedCalendarRoute = EmbedCalendarRouteImport.update({
  id: '/embed/calendar',
  path: '/embed/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/embed/calendar': typeof EmbedCalendarRoute
  '/embed/priests': typeof EmbedPriestsRoute
  '/embed/services': typeof EmbedServicesRoute
  '/embed/spotlight': typeof EmbedSpotlightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/embed/calendar': typeof EmbedCalendarRoute
  '/embed/priests': typeof EmbedPriestsRoute
  '/embed/services': typeof EmbedServicesRoute
  '/embed/spotlight': typeof EmbedSpotlightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/embed/calendar': typeof EmbedCalendarRoute
  '/embed/priests': typeof EmbedPriestsRoute
  '/embed/services': typeof EmbedServicesRoute
  '/embed/spotlight': typeof EmbedSpotlightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/embed/calendar'
    | '/embed/priests'
    | '/embed/services'
    | '/embed/spotlight'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/embed/calendar'
    | '/embed/priests'
    | '/embed/services'
    | '/embed/spotlight'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/embed/calendar'
    | '/embed/priests'
    | '/embed/services'
    | '/embed/spotlight'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EmbedCalendarRoute: typeof EmbedCalendarRoute
  EmbedPriestsRoute: typeof EmbedPriestsRoute
  EmbedServicesRoute: typeof EmbedServicesRoute
  EmbedSpotlightRoute: typeof EmbedSpotlightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/spotlight': {
      id: '/embed/spotlight'
      path: '/embed/spotlight'
      fullPath: '/embed/spotlight'
      preLoaderRoute: typeof EmbedSpotlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/services': {
      id: '/embed/services'
      path: '/embed/services'
      fullPath: '/embed/services'
      preLoaderRoute: typeof EmbedServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/priests': {
      id: '/embed/priests'
      path: '/embed/priests'
      fullPath: '/embed/priests'
      preLoaderRoute: typeof EmbedPriestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/calendar': {
      id: '/embed/calendar'
      path: '/embed/calendar'
      fullPath: '/embed/calendar'
      preLoaderRoute: typeof EmbedCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EmbedCalendarRoute: EmbedCalendarRoute,
  EmbedPriestsRoute: EmbedPriestsRoute,
  EmbedServicesRoute: EmbedServicesRoute,
  EmbedSpotlightRoute: EmbedSpotlightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
